name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    environment: build
    # env:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/dev.yaml
        channels: conda-forge,nodefaults
        activate-environment: adcaptura
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Update all submodules
      run: |
        git submodule update --init --recursive

    - name: Build
      run: docker build -t adanalise .

    - name: Test
      run: docker run adanalise arg1 arg2 arg3
